### ISSUE TITLE
[math mistake] Ошибка в определении нормы для вектор-функции

### ISSUE THREAD

**Issue by PishchevPM** [MIPT-tex/Differential-equations#24]
Билет 4
Пункт 4.1
Страница 37
В определении нормы вектор-функции элемент вектор-функции указан без модуля. Норма всегда должна быть неотрицательной.
Неправильно:
max(max(x^i(t))
Правильно:
max(max(|x^i(t)|))

**Comment by Vokerlee** [comment]
Спасибо
